AWSTemplateFormatVersion: '2010-09-09'
Description: This is template for activity 2
Parameters:
  vpccidr:
    Description: This is cidr for vpc
    Type: String
    Default: 192.168.0.0/16
Resources:
  ntiervpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: vpccidr
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: Ntier